dot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from django import urls

urlpatterns = [
    path('dot/superuser/', admin.site.urls),
    path('', include('dot_app.urls')),
    # path('api/',include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
# urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

dot_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.contrib.auth.hashers import make_password
from django_filters import FilterSet


class destarea_type(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)

class destination_area(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)
    place = models.CharField(max_length=100, default=None, blank=True)
    description = models.TextField(max_length=200, default=None, blank=True)    
    image = models.ImageField(upload_to = 'images/', blank=True)
    country = models.CharField(max_length=100, default=None, blank=True)
    state = models.CharField(max_length=100, default=None, blank=True) 
    lattitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    status = models.BooleanField()
    c_user = models.CharField(max_length=100, default=None, blank=True)

class destinationarea_type(models.Model):
    destnarea_type = models.ForeignKey(destarea_type, default=None, on_delete=models.CASCADE)
    destnarea = models.ForeignKey(destination_area, default=None, on_delete=models.CASCADE)

class destination_type(models.Model):
    name = models.CharField(max_length=50, blank=True, default=None)
    description = models.CharField(max_length=200, default=None, blank=True)
    status = models.BooleanField(default=False)

class destinstions(models.Model):
    name = models.CharField(max_length=100, default=None, blank=True)
    d_area = models.ForeignKey(destination_area, default=None, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, default=None, blank=True)
    description = models.TextField(max_length=200, default=None, blank=True)    
    culture = models.TextField(max_length=200, default=None, blank=True)
    climate = models.TextField(max_length=200, default=None, blank=True)
    lattitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    status = models.BooleanField(default=False)
    c_user = models.CharField(max_length=100, default=None, blank=True)
    destn_type = models.CharField(max_length=100, default=None, blank=True)

class destination_img(models.Model):
    destinstions = models.ForeignKey(destinstions, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'images/', blank=True)

class destn_geography(models.Model):
    destinstions = models.ForeignKey(destinstions, default=None, on_delete=models.CASCADE)
    types = models.CharField(max_length=100, default=None, blank=True)
    title = models.CharField(max_length=100, default=None, blank=True)
    description = models.CharField(max_length=200, default=None, blank=True)
    status = models.BooleanField(default=False)

class country(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)
    location = models.CharField(max_length=200, default=None, blank=True)
    lattitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    status = models.BooleanField(default=False)

class state(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)
    location = models.CharField(max_length=200, default=None, blank=True)
    lattitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    country_id = models.ForeignKey(country, default=None, on_delete=models.CASCADE)  
    status = models.BooleanField(default=False)

class city(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)
    location = models.CharField(max_length=200, default=None, blank=True)
    lattitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, default=None, blank=True)
    state_id = models.ForeignKey(state, default=None, on_delete=models.CASCADE)  
    status = models.BooleanField(default=False)

class hotel_type(models.Model):
    types = models.CharField(max_length=200, default=None, blank=True)
    
class organization(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=200,blank=True, null=True)
    org_type = models.CharField(max_length=200,blank=True, null=True)
    destinstion = models.ForeignKey(destinstions, default=None, on_delete=models.CASCADE)  
    contact_person = models.CharField(max_length=200,blank=True, null=True)
    contact_number = models.CharField(max_length=200,blank=True, null=True)
    website = models.CharField(max_length=200,blank=True, null=True)
    city = models.ForeignKey(city, default=None, on_delete=models.CASCADE) 
    state = models.ForeignKey(state, default=None, on_delete=models.CASCADE) 
    address = models.CharField(max_length=200,blank=True, null=True)
    phone = models.CharField(max_length=200,blank=True, null=True)
    email = models.EmailField(max_length=200,blank=True, null=True)
    proof = models.CharField(max_length=200,blank=True, null=True)
    status = models.BooleanField(default=True)
    c_user = models.CharField(max_length=100, default=None, blank=True)

class facility_type(models.Model):
    title = models.CharField(max_length=100,blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    status = models.BooleanField(default=False)

class destn_facility(models.Model):
    destinstions = models.CharField(max_length=100, default=None, blank=True)
    orgatn = models.CharField(max_length=100, default=None, blank=True)
    title = models.CharField(max_length=100, default=None, blank=True)
    description = models.CharField(max_length=200, default=None, blank=True)
    types = models.CharField(max_length=100, default=None, blank=True)
    amount = models.FloatField(default=None, blank=True)
    status = models.BooleanField(default=False)
    c_user = models.CharField(max_length=100, default=None, blank=True)

class facility_price(models.Model):
    dstn_facility = models.ForeignKey(destinstions, default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default=None, blank=True)
    amount = models.FloatField(default=None, blank=True)
    discount = models.FloatField(default=None, blank=True)
    total = models.FloatField(default=None, blank=True)
    status = models.BooleanField(default=False)

class facility_image(models.Model):
    destinstion =  models.CharField(max_length=100, default=None, blank=True)
    facility = models.ForeignKey(destn_facility, default=None, on_delete=models.CASCADE) 
    imagetype = models.CharField(max_length=200, default=None, blank=True)
    image = models.ImageField(upload_to = 'images/', blank=True)
    status = models.BooleanField(default=False)
    c_user = models.CharField(max_length=100, default=None, blank=True)

class organization_images(models.Model):
    organization = models.ForeignKey(organization, default=None, on_delete=models.CASCADE) 
    images = models.ImageField(upload_to = 'images/', blank=True)

class userprofile(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default=None, blank=True)
    phone = models.CharField(max_length=200,blank=True, null=True)
    address = models.CharField(max_length=200,blank=True, null=True)
    # hotel_type = models.CharField(max_length=200,blank=True, null=True)
    # contact_person = models.CharField(max_length=200,blank=True, null=True)
    # organization = models.ForeignKey(organization, default=None, on_delete=models.CASCADE) 
    # city = models.CharField(max_length=200,blank=True, null=True)
    # state = models.CharField(max_length=200,blank=True, null=True)
    # country = models.CharField(max_length=200,blank=True, null=True)
    # email = models.EmailField(max_length=200,blank=True, null=True)
    status = models.BooleanField(default=False)
    c_user = models.CharField(max_length=100, default=None, blank=True)
    
class content(models.Model):
    content_type = models.CharField(max_length=200,blank=True, null=True)
    title = models.CharField(max_length=200,blank=True, null=True)
    page = models.CharField(max_length=200,blank=True, null=True)
    path = models.CharField(max_length=200,blank=True, null=True)
    body = models.CharField(max_length=200,blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True)
    updated = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    c_user = models.CharField(max_length=200,blank=True, null=True)

class content_images(models.Model):
    cid = models.CharField(max_length=200,blank=True, null=True)
    content = models.CharField(max_length=200,blank=True, null=True)
    image = models.ImageField(upload_to = 'images/', blank=True)
    overlay = models.CharField(max_length=200,blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True)
    status =  models.BooleanField(default=False)
    c_user = models.CharField(max_length=200,blank=True, null=True)

class faq_category(models.Model):
    name = models.CharField(max_length=200,blank=True, null=True)
    description = models.CharField(max_length=200,blank=True, null=True)
    popularity = models.CharField(max_length=200,blank=True, null=True, default='0')
    status =  models.BooleanField(default=False,blank=True, null=True,)

class faq(models.Model):

templates/addstaff.html
{% extends "./base1.html" %}

{% block main %}
<main class="col-md-9 bgmain ms-sm-auto col-lg-10 px-md-4">     
                                        
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
            <h1 class="h4">Add Staff
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/dot">Home</a></li>
                <li class="breadcrumb-item">Add User</li>
              </ol>
            </h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              
              <div class="btn-group me-2">
                <a href="/dot/stafflist/"><button type="button" class="btn btn-sm">Staff List</button></a>
              </div>
           
            </div>
          </div>
          <div class="card p-4 rounded-1 border-0 shadow">
            <h5 class="text-uppercase fw-bold mb-4 col-8">&nbsp;</h5>
            <div class="" >
              <form class="form-horizontal" method="POST" action="/dot/savestaff/" enctype="multipart/form-data" >{% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label for="username" class="form-label">User Name</label>
                        <input type="text" class="form-control" name="username" value="" id="username" required><br>
                    </div>
                    <div class="col-md-4">
                        <label for="first_name" class="form-label">First name</label>
                        <input type="text" class="form-control" name="first_name" value="" id="first_name" required><br>
                    </div>        
                    <div class="col-md-4">
                      <label for="last_name" class="form-label">Last Name</label>
                      <input type="text" class="form-control" name="last_name" value="" id="last_name" required><br>
                    </div>
                    <div class="col-md-4">
                      <label for="email" class="form-label">Email</label>
                      <input type="email" class="form-control" name="email" value="" id="email" required><br>
                    </div>
                    <div class="col-md-4">
                      <label for="password" class="form-label">Password</label>
                      <input type="password" class="form-control" name="password" value="" id="password" required><br>
                    </div>
                    <div class="col-md-4">
                      <label for="password_confirmation" class="form-label">Password confirmation</label>
                      <input type="password" class="form-control" name="password_confirmation" value="" id="password_confirmation" required><br>
                    </div>
                    <div class="col-md-4">
                        <label for="contact_number" class="form-label">Contact Number</label>
                        <input type="text" class="form-control" name="contact_number" value="" id="contact_number" required><br>
                    </div>
                    <div class="col-md-8">
                        <label for="address" class="form-label">Address</label>
                        <input type="text" class="form-control" name="address" value="" id="address" required><br>
                    </div>
                    <div class="col-md-4">
                        <label for="roll" class="form-label">Roll</label>
                        <select name="roll" id="roll" class="form-control" >
                            <option value="0">--Select--</option>    
                            {% for x in gp %}
                            <option value="{{x.id}}">{{x.name}}</option><br>
                            {% endfor %}
                            </select> 
                    </div>

                    <div class="col-md-6"><br>
                        <label for="status">Status </label>
                        <input type="checkbox" id="status" name="status" value="True">
                        
                    </div>

                    
                 
                  {% if user.is_superuser %}
                    <div class="col-md-4"><br><br>
                      <label for="title" class="form-label">Staff</label>
                      <div class="col">{{ form.is_staff }}</div>
                    </div>
                  {% endif %}
                   
                  <div class="col-12 mt-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
                </form>

        </div>
        </div>
</main>
{% endblock %}  

templates/bookinglist.html
{% extends "./base1.html" %}

{% block main %}
  <main class="col-md-9 bgmain ms-sm-auto col-lg-10 px-md-4">
     
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
        <h1 class="h4">Booking List
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dot/">Home</a></li>
            <li class="breadcrumb-item">Booking List</li>
          </ol></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-toolbar mb-2 mb-md-0">
              {% if perms.dot_app.add_hotel %}
                <div class="btn-group me-2">
                  <a href="/dot/exportbookinglist/"><button type="button" class="btn btn-sm">Export</button></a>
                </div>
                {% endif %}
              </div>
        </div>
      </div>
      
      <div class="table-responsive card rounded-1 border-0 shadow mt-4 mb-4">
            <h5 class="text-uppercase fw-bold mb-0 p-4 pt-3 pb-3">Booking List</h5>
            <form method="post" action="/dot/approvebooking/" enctype="multipart/form-data" >{% csrf_token %}
            <table id="example" class="table table-striped table-sm">
            
              <thead>
                <tr> 
                  <th scope="col">CUSTOMER</th>
                  <th scope="col">TITLE</th>                             
                  <th scope="col">BOOKING TYPE</th>
                  <th scope="col">FROM</th>
                  <th scope="col">TO</th>
                  <th scope="col">CREATED DATE</th>
                  <th scope="col">UPDATED DATE</th>
                  <th scope="col">STATUS</th>
                  <th> <input type="checkbox" name="checkallv" class="checkall" value="1"></th>
                </tr>
              </thead>
              <tbody>
                {% for x in c_booking %}
                <tr>
                    <td >{{x.cust.name}}</td> 
                    <td >{{x.title}}</td>
                    <td >{{x.bking_type}}</td>                       
                    <td >{{x.bk_from}}</td> 
                    <td >{{x.bk_to}}</td> 
                    <td >{{x.created}}</td> 
                    <td >{{x.updated}}</td> 
                    <td >{{x.status}}</td> 
                    <td>
                      <input type="checkbox" name="checkbook " class="bulklv checkme" value="{{x.id}}">
                    </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!-- <div class="row">    
              <div class="btn-group me-2 d-flex p-2 ">
                <div class="btn-toolbar mb-2 mb-md-1 justify-content-end ">
                  

                  <div class="ps-3"><button type="submit" class=" btn btn-primary" name="approve" value="approve" >Approve</button></div>
                  <div class="ps-3"><button type="submit" class=" btn btn-primary" >Delete</button></div>
                </div>
              </div>
            </div> -->
            <!-- <a href="/dot/edit_destinationarea/?a={{x.id}}"><button class="btn btn-primary" >Approve</button></a> -->
            {% if perms.dot_app.change_booking %}
            <div style="border-top:1px solid #ccc; margin-top: 50px; padding: 5px;">
              <div class="row float-end">
                <div class="col-md-12 ">
                  <button type="submit" class=" btn btn-primary" name="approve" value="approve" >Approve</button>
                  {% if perms.dot_app.delete_booking %}
                  <button type="submit" class=" btn btn-primary" >Delete</button>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endif %}
          </form>
    </div>   

  </main>
{% endblock %}  

templates/destinationarea.html
{% extends "./base1.html" %}
{% block main %}
  <main class="col-md-9 bgmain ms-sm-auto col-lg-10 px-md-4">     
                                        
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
        <h1 class="h4">Destination Area
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin/">Home</a></li>
            <li class="breadcrumb-item">Destination Area</li>
          </ol>
        </h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <a href="/dot/view_destinationarea/"><button type="button" class="btn btn-sm">Destination Area List</button></a>
          </div>
        </div>
      </div>
      <div class="card p-4 rounded-1 border-0 shadow">
        <h5 class="text-uppercase fw-bold mb-4 col-8">&nbsp;</h5>

        <form class="form-horizontal" method="POST" action="/dot/add_destination_area/" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">
            <div class="col-md-4">
              <label for="inputcountry" class="form-label">Country</label>
              <select id="country" name="country" class="form-select" onchange="get_country()">
                <option value="0">Choose...</option>
                {% for x in country %}
                <option value="{{x.id}}">{{x.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-md-4">
              <label for="inputState" class="form-label">State</label>
              <select id="state" name="state" class="form-select">
                <option value="0">Choose...</option>
                {% for x in state %}
                <option value="{{x.id}}">{{x.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-md-4">
              <label for="destinationarea_type" class="form-label">Destination Area Type</label>
              <select id="destinationarea_type" name="destinationarea_type" class="form-select " multiple >
                
                {% for x in destarea_type %}
                <option value="{{x.id}}" aria-multiselectable="true">{{x.name}}</option>
                {% endfor %}
              </select><br>
            </div>
              <div class="col-md-4">
                <label for="title" class="form-label">Destination Area</label>
                <input type="text" class="form-control" name="destn_area" id="destn_area" required><br>
              </div>
              
              <div class="col-md-4">
                <label for="place" class="form-label">Place</label>
                <input type="text" class="form-control" name="place" id="place" required><br>
              </div>
              <div class="col-md-4">
                <label for="description" class="form-label">description</label>
                <input type="text" class="form-control" name="description" id="description" required><br>
              </div>
              <div class="col-md-4">
                <label for="lattitude" class="form-label">Lattitude</label>
                <input type="text" class="form-control" name="lattitude" id="lattitude" required><br>
              </div>
              <div class="col-md-4">
                <label for="longitude" class="form-label">Longitude</label>
                <input type="" class="form-control" name="longitude" id="longitude" required><br>
              </div>
              <div class="col-md-4">
                <label for="images" class="form-label">Choose Images</label><br>
                  <input type="file" class="form-control"  placeholder="" name="image" id="image" required>
                </div> 
              
              <div class="col-md-6">
                <label for="status" class="form-label">Status </label>
                <input type="checkbox" id="status" name="status" value="True">
                
              </div>
                 
            </div>
            
            <div class="col-12 mt-4">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
      </div>
      
    
  
    </main>
    </div>
    </div>
    <script>
    document.getElementById('output').innerHTML = location.search;
    $(".chosen-select").chosen();
  </script>

{% endblock %}

templates/edit_destinationarea.html
{% extends "./base1.html" %}
{% block main %}
  <main class="col-md-9 bgmain ms-sm-auto col-lg-10 px-md-4">     
                                        
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
        <h1 class="h4">Edit Destination Area
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin/">Home</a></li>
            <li class="breadcrumb-item">Edit Destination Area</li>
          </ol>
        </h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          {% if perms.dot_app.view_destination_area %}
          <div class="btn-group me-2">
            <a href="/dot/view_destinationarea/"><button type="button" class="btn btn-sm">View Destination Area</button></a>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="card p-4 rounded-1 border-0 shadow">
        <h5 class="text-uppercase fw-bold mb-4 col-8">&nbsp;</h5>
        

        <form class="form-horizontal" method="POST" action="/dot/update_destinationarea/" enctype="multipart/form-data">{% csrf_token %}
          {% for x in destn %}
          <div class="row">
            <div class="col-md-4">
              <label for="country" class="form-label">Country</label>
              <input type="text" class="form-control" name="country" id="country" value="{{x.country}}" readonly required><br>
            </div>
            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <input type="text" class="form-control" name="state" id="state" value="{{x.state}}" readonly required><br>
            </div>
            <div class="col-md-4">
              <label for="destinationarea_type" class="form-label">Destination Area Type</label>
              <select id="destinationarea_type" name="destinationarea_type" class="form-select " multiple >
                {% for d in destarea_type %}
                <option value="{{d.id}}" aria-multiselectable="true" {% if d.id in d_type_list %}selected{% endif %}>{{d.name}}</option>
                {% endfor %}
              </select><br>
            </div>
              <div class="col-md-4">
                <label for="title" class="form-label">Destination Area</label>
                <input type="text" class="form-control" name="da_id" id="da_id" value="{{x.id}}" hidden required> 

                <input type="text" class="form-control" name="destn_area" id="destn_area" value="{{x.name}}" required>
                
              </div>
              
              <div class="col-md-4">
                <label for="place" class="form-label">Place</label>
                <input type="text" class="form-control" name="place" id="place" value="{{x.place}}" required><br>
              </div>
              <div class="col-md-4">
                <label for="lattitude" class="form-label">Lattitude</label>
                <input type="text" class="form-control" name="lattitude" id="lattitude" value="{{x.lattitude}}" required><br>
              </div>
              <div class="col-md-4">
                <label for="longitude" class="form-label">Longitude</label>
                <input type="text" class="form-control" name="longitude" id="longitude" value="{{x.longitude}}" required><br>
              </div>
              <div class="col-md-4">
                <label for="images" class="form-label">Choose Images</label><br>
                  <input type="file" class="form-control"  placeholder="" name="image" id="image" >
              </div> 
              <div class="col-md-4">
                <label for="status" class="form-label">Status </label>
                <input type="checkbox" id="status" name="status" value="1" {% if x.status %}checked{% endif %}/>
              </div>
              <div class="row" style="display:inline-flex"  data-wow-delay="1.3s">
                <div class="col-md-8 ">
                  <div class="imageField" style="margin-left:0;margin-top: 4rem;">
                    <div class="card" style="width: 15rem;">
                      <img class="card-img-top" src="{{x.image.url}}" alt="Card image cap">
                    </div><br>
                    <!-- <div class="btn-group me-6" >
                      <button type="button" style="margin-left: 7rem" class="btn-link border-0 bg-transparent text-body " onClick="confdelete(this, '{{x.id}}');"><span data-feather="trash-2" ></span></button>
                    </div> -->
                    <!-- <input type="text" class="form-control" id="inpu" name="pla" id="place" value="{{c.id}}"><br><br> -->
                    <br>
                  </div>
                </div>
              </div>
             
                 
          </div>
            
          <div class="col-12 mt-4">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
          {% endfor %}
        </form>
          
      </div>
      
    
  
    </main>
    </div>
    </div>

{% endblock %}

templates/editfaq.html
{% extends "./base1.html" %}
{% block main %}

<main class="col-md-9 bgmain ms-sm-auto col-lg-10 px-md-4">     
                                        
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
            <h1 class="h4">Edit FAQ
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/dot">Home</a></li>
                <li class="breadcrumb-item">Edit FAQ</li>
                </ol>
            </h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                <a href="/dot/viewfaqlist"><button type="button" class="btn btn-sm">FAQ List</button></a>
                </div>
            </div>
        </div>
        <div class="card p-4 rounded-1 border-0 shadow">
            <h5 class="text-uppercase fw-bold mb-4 col-8">&nbsp;</h5>
            <div class="row" style="margin-left: .5rem;">
            <form class="form-horizontal" method="POST" action="/dot/updatefaq/" enctype="multipart/form-data">{% csrf_token %}
                <div class="row">
                {% for x in faq %}
                    <div class="col-md-6">
                        <label for="category_type"  class="form-label">Category</label><br>
                            <select name="category_type" id="category_type" class="form-control">
                                <option value="{{x.category}}">{{x.category}}</option> 
                                {% for x in fq_category %}
                                <option value="{{x.name}}">{{x.name}}</option>
                                {% endfor %}
                            </select>  
                    </div>
                    <div class="col-md-6">
                      <label for="title" class="form-label">Title</label>
                      <input type="hidden" class="form-control" name="id" value="{{x.id}}" id="id" required><br>
                      <input type="text" class="form-control" name="title" value="{{x.title}}" id="title" required><br>
                    </div>
                    <div class="col-md-6">
                      <label for="description" class="form-label">Description</label>
                      <input type="text" class="form-control" name="description" value="{{x.description}}" id="description" required><br>
                    </div>
                    <div class="col-md-6">
                        <label for="status">Status </label>
                        
                        <input type="checkbox" id="status" name="status" value="1" {% if x.status %}checked{% endif %}/>
                    </div>
                {% endfor %}
                    <div class="col-12 mt-4">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
            </form> 
            </div>
        </div>
</main>
{% endblock %}  